title: Hi, I am Sudarshini aka Sudo
logo: "/images/profile.png"
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters student at NYU studying Computer Science and Data Science
  <br><br>
  President - <a href="https://cssocialgood.github.io">CS+Social Good @ NYU</a> | Board @ <a href="https://techshift.org">TechShift</a>
  <br><br>
  Looking for full time opportunities as Machine Learning Engineer or Data Scientist starting June 2020.
  <br><br>
  <a href="https://www.linkedin.com/in/sudarshini-tyagi/">View My LinkedIn Profile</a> 
theme: jekyll-theme-minimal
